# Generated by Django 2.2.19 on 2022-01-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voditeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_vod', models.CharField(max_length=30, verbose_name='Имя и Фамилия')),
                ('Date_of_birth', models.CharField(max_length=10, verbose_name='Дата рождения')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('Auto', models.TextField(max_length=20, verbose_name='Автомобиль')),
                ('Auto_number', models.CharField(max_length=10, verbose_name='госномер')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
