# Generated by Django 2.2.19 on 2022-01-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voditeli',
        ),
    ]
