# Generated by Django 2.2.19 on 2022-01-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_cheif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chiefs', to='employee.Employee')),
                ('full_name_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='employee.Employee')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
