# Generated by Django 2.2.19 on 2022-01-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_chief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chief',
            old_name='full_name_cheif',
            new_name='full_name_chief',
        ),
    ]
