# Generated by Django 2.2.19 on 2022-01-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20220102_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='full_name_chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='chief',
            name='full_name_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_employee', to='employee.Employee'),
        ),
    ]
