# Generated by Django 2.2.19 on 2022-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20220103_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=15, verbose_name='Должность'),
        ),
    ]
